### ISSUE TITLE
Support for defaultProps will be removed from function components in a future major release

### ISSUE THREAD

**Issue by MariamKhojashvili** [jakezatecky/react-dual-listbox#248]
**Describe the bug**
Hi, this message keeps showing up in the terminal are you planning to update the cod so this warning will go away?

`Warning: Action: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at Action (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_react-dual-listbox_lib_index_77fd12.js:1284:29)
    at div
    at div
    at div
    at div
    at DualListBox (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_react-dual-listbox_lib_index_77fd12.js:127:25)
    at FilterExample (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/src_19d23f._.js:64:249)
    at form
    at FormProvider (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_react-hook-form_dist_index_esm_mjs_0e3dff._.js:151:13)
    at BackTesterForm (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/src_19d23f._.js:909:180)
    at Lazy
    at div
    at InnerLayoutRouter (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_09c837._.js:11958:11)
    at RedirectErrorBoundary (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_a577e5._.js:8410:9)
    at RedirectBoundary (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_a577e5._.js:8418:11)
    at NotFoundBoundary (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_a577e5._.js:8120:11)
    at LoadingBoundary (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_09c837._.js:12062:11)
    at ErrorBoundary (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_a577e5._.js:9127:11)
    at InnerScrollAndFocusHandler (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_09c837._.js:11870:9)
    at ScrollAndFocusHandler (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_09c837._.js:11945:11)
    at RenderFromTemplateContext (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_next_dist_04e02c._.js:46:236)
    at Lazy
    at OuterLayoutRouter (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_09c837._.js:12071:11)
    at Lazy
    at div
    at div
    at InnerLayoutRouter (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_09c837._.js:11958:11)
    at RedirectErrorBoundary (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_a577e5._.js:8410:9)
    at RedirectBoundary (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_a577e5._.js:8418:11)
    at NotFoundErrorBoundary (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_a577e5._.js:8112:9)
    at NotFoundBoundary (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_a577e5._.js:8120:11)
    at LoadingBoundary (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_09c837._.js:12062:11)
    at ErrorBoundary (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_a577e5._.js:9127:11)
    at InnerScrollAndFocusHandler (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_09c837._.js:11870:9)
    at ScrollAndFocusHandler (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_09c837._.js:11945:11)
    at RenderFromTemplateContext (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_next_dist_04e02c._.js:46:236)
    at Lazy
    at OuterLayoutRouter (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_09c837._.js:12071:11)
    at Lazy
    at SessionProvider (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/_d71532._.js:1781:26)
    at SessionProvider (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/_d71532._.js:15:28)
    at Lazy
    at Provider (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_b2ef7d._.js:4614:28)
    at $a093c7e1ec25a057$export$f78649fb9ca566b8 (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_b2ef7d._.js:7764:29)
    at f (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_b2ef7d._.js:8313:24)
    at $ (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_b2ef7d._.js:8310:227)
    at ThemeProvider (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/src_8d5482._.js:69:26)
    at Lazy
    at body
    at html
    at RedirectErrorBoundary (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_a577e5._.js:8410:9)
    at RedirectBoundary (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_a577e5._.js:8418:11)
    at ReactDevOverlay (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_a577e5._.js:7220:9)
    at HotReload (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_a577e5._.js:7967:11)
    at Router (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_a577e5._.js:11396:11)
    at ErrorBoundaryHandler (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_a577e5._.js:9098:9)
    at ErrorBoundary (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_a577e5._.js:9127:11)
    at AppRouter (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_a577e5._.js:11674:13)
    at Lazy
    at Lazy
    at /Users/mariamk/Desktop/front-admin-modern/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:380095
    at /Users/mariamk/Desktop/front-admin-modern/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:380095
    at ServerInsertedHTMLProvider (/Users/mariamk/Desktop/front-admin-modern/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:17348)
`
**Reproduction steps**
library versions:
               `"react": "^18.2.0",
		"react-dom": "^18.2.0",
		"react-dual-listbox": "^5.0.2",
		"next": "^14.0.3",
		`
		
I just installed the package and used the component as in the example with filtration. And message above keeps showing up in the terminal.

**Expected behavior**
There is no error in the terminal.
**Screenshots**
<img width="1660" alt="image" src="https://github.com/jakezatecky/react-dual-listbox/assets/74396670/b006040d-b686-4589-ac01-1539a1bab3f7">

**Comment by jakezatecky** [comment]
In case you are unaware, v6 is currently available @MariamKhojashvili .

**Comment by MariamKhojashvili** [comment]
Thank you for letting me know @jakezatecky

**Comment by MariamKhojashvili** [comment]
is this the common issue? I am having it after updating to 6.0.0

`⨯ node_modules/react-dual-listbox/lib/index.js (2541:0) @ Array.<anonymous>
 ⨯ ReferenceError: Element is not defined
    at Array.<anonymous> (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_react-dual-listbox_lib_index_77fd12.js:1896:95)
    at __webpack_require__ (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_react-dual-listbox_lib_index_77fd12.js:3852:51)
    at Array.hasOwn (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_react-dual-listbox_lib_index_77fd12.js:957:90)
    at __webpack_require__ (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_react-dual-listbox_lib_index_77fd12.js:3852:51)
    at Array.<anonymous> (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_react-dual-listbox_lib_index_77fd12.js:859:86)
    at __webpack_require__ (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_react-dual-listbox_lib_index_77fd12.js:3852:51)
    at Array.<anonymous> (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_react-dual-listbox_lib_index_77fd12.js:30:104)
    at __webpack_require__ (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_react-dual-listbox_lib_index_77fd12.js:3852:51)
    at /Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_react-dual-listbox_lib_index_77fd12.js:3903:92
    at /Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_react-dual-listbox_lib_index_77fd12.js:3905:11
    at /Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_react-dual-listbox_lib_index_77fd12.js:3907:16
    at webpackUniversalModuleDefinition (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_react-dual-listbox_lib_index_77fd12.js:10:85)
    at Object.<anonymous> (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/node_modules_react-dual-listbox_lib_index_77fd12.js:14:3)
    at instantiateModule (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/[turbopack]_runtime.js:452:23)
    at getOrInstantiateModuleFromParent (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/[turbopack]_runtime.js:502:12)
    at esmImport (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/[turbopack]_runtime.js:110:20)
    at /Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/src_15f6da._.js:1392:153
    at [project]/src/components/dual-lisbox/dual-listbox.tsx [ssr] (ecmascript) (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/src_15f6da._.js:1508:3)
    at instantiateModule (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/[turbopack]_runtime.js:452:23)
    at getOrInstantiateModuleFromParent (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/[turbopack]_runtime.js:502:12)
    at esmImport (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/[turbopack]_runtime.js:110:20)
    at /Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/src_15f6da._.js:1745:152
    at [project]/src/app/admin/back-tester/components/common-fields.tsx [ssr] (ecmascript) (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/src_15f6da._.js:1989:3)
    at instantiateModule (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/[turbopack]_runtime.js:452:23)
    at getOrInstantiateModuleFromParent (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/[turbopack]_runtime.js:502:12)
    at esmImport (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/[turbopack]_runtime.js:110:20)
    at /Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/src_15f6da._.js:2000:169
    at [project]/src/app/admin/back-tester/components/form.tsx [ssr] (ecmascript) (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/src_15f6da._.js:2341:3)
    at instantiateModule (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/[turbopack]_runtime.js:452:23)
    at getOrInstantiateModuleFromParent (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/[turbopack]_runtime.js:502:12)
    at esmImport (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/[turbopack]_runtime.js:110:20)
    at /Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/src_15f6da._.js:3188:157
    at [project]/src/app/admin/back-tester/page.tsx [ssr] (ecmascript) (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/src_15f6da._.js:3284:3)
    at instantiateModule (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/[turbopack]_runtime.js:452:23)
    at getOrInstantiateModuleFromParent (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/[turbopack]_runtime.js:502:12)
    at commonJsRequire (/Users/mariamk/Desktop/front-admin-modern/.next/server/chunks/[turbopack]_runtime.js:124:20)
`

@jakezatecky

**Comment by jakezatecky** [comment]
The above was resolved in #259.
